"""create_initial_schema

Revision ID: 0001
Revises:
Create Date: 2026-09-12

This migration is written by hand (not autogenerated) because it relies on
Supabase/Postgres-specific features that Alembic cannot infer reliably:
  - pgvector extension
  - vector(1536) embedding column
  - generated TSVECTOR column
  - HNSW index for vector similarity search
  - GIN index for full-text search
  - Row Level Security (RLS) policies
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the initial Document Copilot schema."""

    # ------------------------------------------------------------------
    # 0. Extensions
    # pgvector must exist before vector(1536) columns can be created.
    # ------------------------------------------------------------------
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ------------------------------------------------------------------
    # 1. users
    #    Mirrors Supabase auth.users — each row is a verified analyst.
    #    id comes from Supabase Auth, so no server-side default needed.
    # ------------------------------------------------------------------
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("email", sa.String(255), nullable=False, unique=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index("ix_users_email", "users", ["email"])

    # ------------------------------------------------------------------
    # 2. chat_threads
    # ------------------------------------------------------------------
    op.create_table(
        "chat_threads",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "title",
            sa.String(255),
            server_default=sa.text("'New Chat'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index("ix_chat_threads_user_id", "chat_threads", ["user_id"])

    # ------------------------------------------------------------------
    # 3. chat_messages
    # ------------------------------------------------------------------
    op.create_table(
        "chat_messages",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "thread_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("chat_threads.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("role", sa.String(50), nullable=False),
        sa.Column("content", sa.Text, nullable=False),
        sa.Column("parts", postgresql.JSONB, nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index("ix_chat_messages_thread_id", "chat_messages", ["thread_id"])

    # ------------------------------------------------------------------
    # 4. source_documents
    # ------------------------------------------------------------------
    op.create_table(
        "source_documents",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("ticker", sa.String(10), nullable=False),
        sa.Column("company", sa.String(255), nullable=False),
        sa.Column("form", sa.String(20), nullable=False),
        sa.Column("filing_date", sa.Date, nullable=False),
        sa.Column("report_date", sa.Date, nullable=True),
        sa.Column("year", sa.Integer, nullable=False),
        sa.Column("accession_number", sa.String(50), nullable=False, unique=True),
        sa.Column("source_url", sa.Text, nullable=False),
        sa.Column("markdown", sa.Text, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index("ix_source_documents_ticker", "source_documents", ["ticker"])
    op.create_index("ix_source_documents_year", "source_documents", ["year"])
    op.create_index(
        "ix_source_documents_accession_number",
        "source_documents",
        ["accession_number"],
    )

    # ------------------------------------------------------------------
    # 5. document_chunks
    #    embedding and search_vector are added via op.execute because they
    #    use Postgres-specific types that SQLAlchemy cannot express natively
    #    in a portable way (vector(1536) from pgvector, generated TSVECTOR).
    # ------------------------------------------------------------------
    op.create_table(
        "document_chunks",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "document_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("source_documents.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("chunk_index", sa.Integer, nullable=False),
        sa.Column("page", sa.Integer, nullable=True),
        sa.Column("section", sa.String(255), nullable=True),
        sa.Column("content", sa.Text, nullable=False),
        sa.Column("token_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column(
            "metadata_json",
            postgresql.JSONB,
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_document_chunks_document_id", "document_chunks", ["document_id"]
    )

    # pgvector embedding column
    op.execute("ALTER TABLE document_chunks ADD COLUMN embedding vector(1536)")

    # Generated TSVECTOR column for full-text search over chunk content
    op.execute(
        """
        ALTER TABLE document_chunks
        ADD COLUMN search_vector tsvector
        GENERATED ALWAYS AS (to_tsvector('english', content)) STORED
        """
    )

    # HNSW index for approximate nearest-neighbour vector search
    op.execute(
        """
        CREATE INDEX ix_document_chunks_embedding_hnsw
        ON document_chunks
        USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64)
        """
    )

    # GIN index for full-text search
    op.execute(
        """
        CREATE INDEX ix_document_chunks_search_vector_gin
        ON document_chunks
        USING gin (search_vector)
        """
    )

    # ------------------------------------------------------------------
    # 6. message_citations
    # ------------------------------------------------------------------
    op.create_table(
        "message_citations",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "message_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("chat_messages.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "chunk_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("document_chunks.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("ticker", sa.String(10), nullable=False),
        sa.Column("company", sa.String(255), nullable=False),
        sa.Column("form", sa.String(20), nullable=False),
        sa.Column("filing_date", sa.Date, nullable=False),
        sa.Column("year", sa.Integer, nullable=True),
        sa.Column("accession_number", sa.String(50), nullable=True),
        sa.Column("page", sa.Integer, nullable=True),
        sa.Column("section", sa.String(255), nullable=True),
        sa.Column("source_url", sa.Text, nullable=True),
        sa.Column("excerpt", sa.Text, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_message_citations_message_id", "message_citations", ["message_id"]
    )
    op.create_index("ix_message_citations_chunk_id", "message_citations", ["chunk_id"])

    # ------------------------------------------------------------------
    # 7. Row Level Security
    #    Each table gets RLS enabled.
    #    User-owned tables are scoped to auth.uid().
    #    source_documents and document_chunks are read-only for all
    #    authenticated users; the ingest script runs as service role and
    #    bypasses RLS automatically.
    # ------------------------------------------------------------------
    for table in (
        "users",
        "chat_threads",
        "chat_messages",
        "message_citations",
        "source_documents",
        "document_chunks",
    ):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")

    # users: own row only
    op.execute(
        """
        CREATE POLICY users_own_row ON users
        FOR ALL
        USING (id = auth.uid())
        WITH CHECK (id = auth.uid())
        """
    )

    # chat_threads: scoped to owning user
    op.execute(
        """
        CREATE POLICY chat_threads_own ON chat_threads
        FOR ALL
        USING (user_id = auth.uid())
        WITH CHECK (user_id = auth.uid())
        """
    )

    # chat_messages: accessible if the parent thread belongs to the user
    op.execute(
        """
        CREATE POLICY chat_messages_own ON chat_messages
        FOR ALL
        USING (
            thread_id IN (
                SELECT id FROM chat_threads WHERE user_id = auth.uid()
            )
        )
        WITH CHECK (
            thread_id IN (
                SELECT id FROM chat_threads WHERE user_id = auth.uid()
            )
        )
        """
    )

    # message_citations: accessible if the parent message belongs to the user
    op.execute(
        """
        CREATE POLICY message_citations_own ON message_citations
        FOR ALL
        USING (
            message_id IN (
                SELECT cm.id FROM chat_messages cm
                JOIN chat_threads ct ON cm.thread_id = ct.id
                WHERE ct.user_id = auth.uid()
            )
        )
        WITH CHECK (
            message_id IN (
                SELECT cm.id FROM chat_messages cm
                JOIN chat_threads ct ON cm.thread_id = ct.id
                WHERE ct.user_id = auth.uid()
            )
        )
        """
    )

    # source_documents: read-only for all authenticated users
    op.execute(
        """
        CREATE POLICY source_documents_read ON source_documents
        FOR SELECT
        USING (auth.role() = 'authenticated')
        """
    )

    # document_chunks: read-only for all authenticated users
    op.execute(
        """
        CREATE POLICY document_chunks_read ON document_chunks
        FOR SELECT
        USING (auth.role() = 'authenticated')
        """
    )


def downgrade() -> None:
    """Drop everything created in upgrade(), in reverse dependency order."""

    # Drop RLS policies first
    for table, policy in (
        ("document_chunks", "document_chunks_read"),
        ("source_documents", "source_documents_read"),
        ("message_citations", "message_citations_own"),
        ("chat_messages", "chat_messages_own"),
        ("chat_threads", "chat_threads_own"),
        ("users", "users_own_row"),
    ):
        op.execute(f"DROP POLICY IF EXISTS {policy} ON {table}")

    # Tables in reverse FK dependency order
    op.drop_table("message_citations")
    op.drop_table("document_chunks")
    op.drop_table("source_documents")
    op.drop_table("chat_messages")
    op.drop_table("chat_threads")
    op.drop_table("users")

    op.execute("DROP EXTENSION IF EXISTS vector")
